### PR TITLE
Support for extracting voice from Amazon Connect produced frames

### PR DESCRIPTION
**Pull request by michalgawlikaws**
*Issue #2:*

*Description of changes:*

Proposed extensions will support extracting voice from Amazon Connect produced frames.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michalgawlikaws** [comment]
Issue #9: should be also addressed with those changes

**Comment by YustinS** [comment]
Just to add to this, the changes work fantastically for processing AWS Connect recordings.
Be great to get merged in.

**Comment by CGarces** [comment]
@YustinS I don't get how record the calls. I have a "Start Media Streaming" block on the connect flow but I don't know how connect the block to the python code. Can you please elaborate a sample?

**Comment by YustinS** [comment]
@CGarces depends on you use case.
For a post call consumption you can look at an example from the Voicemail express repo, which reads the post call CTR from Amazon Connect to get the content. This shows the core of it as needed, you would just need to substitute the input event being from Kinesis to instead be a Connect Lambda invocation if you are going down that path.
https://github.com/amazon-connect/voicemail-express-amazon-connect/blob/main/Code/Core/vmx3_kvs_to_s3.py

If you are trying to process the stream immediately into a lambda function you will need to sub out the the 
`get_media_for_fragment_list` with something like 
```
kvs_media_client.get_media(
            StreamName=self.stream_name,
            StartSelector={
                "StartSelectorType": "FRAGMENT_NUMBER",
                "AfterFragmentNumber": str(self.start_fragment),
            })
```
This may entail some changes to logic since you won't know ahead of time all the fragments, but by consuming the KVS stream should get you going to then play with.

**Comment by CGarces** [comment]
Thanks @YustinS for the hint!
I'll reproduce the functionality of get_media_for_fragment_list

**Pull request merged**
